# Generated by Django 5.2.3 on 2025-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.TextField(default='I am an user'),
        ),
    ]
