# Generated by Django 5.2.3 on 2025-06-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_Mentor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_Team_Lead',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_Team_Mate',
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_ideas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Lead', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
