# Generated by Django 5.2.3 on 2025-06-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_profile_is_mentor_remove_profile_is_team_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.TextField(default='www.github.com'),
        ),
        migrations.CreateModel(
            name='IdeaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_Image', models.ImageField(upload_to='images/')),
                ('Title_of_Idea', models.TextField()),
                ('description', models.TextField()),
                ('website_link', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('date_of_post', models.DateField(auto_now_add=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
