# Generated by Django 5.2.3 on 2025-06-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_github_link_ideacard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacard',
            name='github_link',
            field=models.TextField(default='example.com'),
        ),
    ]
