# Generated by Django 5.2.3 on 2025-06-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_ideacard_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacard',
            name='designation_of_author',
            field=models.TextField(default='member'),
        ),
    ]
