# Generated by Django 5.2.3 on 2025-06-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dashboard.category'),
        ),
    ]
