# Generated by Django 5.2.3 on 2025-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_ideacard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacard',
            name='date_of_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
