# Generated by Django 5.2.3 on 2025-06-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_team_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
            preserve_default=False,
        ),
    ]
