# Generated by Django 5.2.3 on 2025-06-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_profile_designation_profile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacard',
            name='designation_of_author',
        ),
        migrations.AddField(
            model_name='ideacard',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
            preserve_default=False,
        ),
    ]
