# Generated by Django 5.2.3 on 2025-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_ideacard_designation_of_author_ideacard_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Avatar_Image',
            field=models.ImageField(default='images/img.jpeg', upload_to='avatar/'),
        ),
    ]
