# Generated by Django 5.2.3 on 2025-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_profile_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideacard',
            name='avatar_of_Author',
            field=models.TextField(default='avatar.png'),
            preserve_default=False,
        ),
    ]
